# Generated by Django 4.0.3 on 2022-04-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_vaccine_game_age_game_breed_game_sex_game_species_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='vaccinations',
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='gametype',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Vaccine',
        ),
    ]
