# Generated by Django 4.0.3 on 2022-04-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_remove_game_submitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='age',
        ),
        migrations.RemoveField(
            model_name='game',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='game',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='game',
            name='species',
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
