# Generated by Django 4.0.3 on 2022-04-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_remove_game_submission_date_game_console'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='game',
            name='console',
            field=models.CharField(choices=[('P', 'PS5'), ('X', 'XBOX'), ('C', 'PC')], max_length=1),
        ),
    ]
