# Generated by Django 4.0.3 on 2022-04-10 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_rename_name_game_title_alter_game_console'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='console',
            new_name='platform',
        ),
    ]
